name: simple_flag_toggle
description: A library to help you toggle between flags and use a callback function onChanged.
version: 0.0.2
homepage: https://github.com/lopb/simple_flag_toggle
repository: https://github.com/lopb/simple_flag_toggle
issue_tracker: https://github.com/lopb/simple_flag_toggle/issues

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.6.1
  flutter_svg: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  assets:
    - assets/flags/